title: jukang develop blog
description: this blog is develop study place
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jukang3570.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    GangGangGanggang
author-image:   1.jpg
author-job:     Developer
author-email:   asekf122@gmail.com # Add your email for contant form.
about-author:   아직은 이것저것 공부하고 있는 평범한 컴공 대학생입니다. 잘 부탁드립니다! ^^

# Social settings
social-github: jukang3570
social-instagram: jugang_gang

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor